stages:
  load_data:
    cmd: python src/load_data.py
    deps:
      - src/load_data.py
    params:
      - data_source.s3_source
    outs:
      - data/raw/winequality-red.csv

  split_data:
    cmd: python src/split_data.py
    deps:
      - src/split_data.py
      - data/raw/winequality-red.csv
    params:
      - split_data.test_size
      - base.random_state
    outs:
      - data/processed/train_winequality.csv
      - data/processed/test_winequality.csv

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/processed/train_winequality.csv
    params:
      - estimators.ElasticNet.params.alpha
      - estimators.ElasticNet.params.l1_ratio
    outs:
      - models/model.joblib

  evaluate:
    cmd: python src/evaluate.py
    deps:
      - src/evaluate.py
      - data/processed/test_winequality.csv
      - models/model.joblib
    metrics:
      - reports/metrics.json:
          cache: false
